package me.rafique.openfire.auth;

import java.security.Key;

import org.jose4j.jwt.JwtClaims;
import org.junit.Test;

import junit.framework.Assert;
import me.rafique.openfire.auth.KeycloakTokenValidator;

public class KeycloakTokenValidatorTest {

	private KeycloakTokenValidator validator;

	public KeycloakTokenValidatorTest() {

		validator = new KeycloakTokenValidator();
	}

	@Test
	public void testAuthenticateToken() throws Exception {
		String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4WFFDVk5OZjY5c2JTbzQ2OTJaWEh4MXNmX01yaTk4ckY0c3k3UG9OS3dZIn0.eyJqdGkiOiJhOWQ3NmMwNS03NWMzLTRiMTItODNiNy0yOGVkYzhmMWQ3ZmUiLCJleHAiOjE1MjA3Mzk0OTUsIm5iZiI6MCwiaWF0IjoxNTIwNjk2Mjk1LCJpc3MiOiJodHRwczovL3Nzby52cmlnYXRld2F5LmNvbS9hdXRoL3JlYWxtcy9zYW5kYm94IiwiYXVkIjoic2FuZGJveC1hcHAiLCJzdWIiOiI1YmU3YzRiYi0zZDRlLTQ2NjktOGI1Yy1iNWFmOGUzZjU5YzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzYW5kYm94LWFwcCIsImF1dGhfdGltZSI6MTUyMDY5NjI5NSwic2Vzc2lvbl9zdGF0ZSI6ImFhNGU4NjEwLTY1MzMtNDczZC05MTQzLTk0ZDVhNDFlNTE2YyIsImFjciI6IjEiLCJjbGllbnRfc2Vzc2lvbiI6IjcyMmI5OTcyLTNlZjQtNDkwYS1hNzZhLWY0ZjNkNDBkNmRkOSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJCQUJFTF9BRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sIm5hbWUiOiJSYWZpcXVlIEFud2FyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicmFmaXF1ZS5hbndhckBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiUmFmaXF1ZSIsImZhbWlseV9uYW1lIjoiQW53YXIiLCJlbWFpbCI6InJhZmlxdWUuYW53YXJAZ21haWwuY29tIn0.cvYTxiDJczz-QvwveqU-U9uqN6877NZAD-VgqK4TkwoSNIcg0HDdVhuCzLcKBtoitej_znb8_0qDfLcHS6O2q0xJYJ2_r26rt6obGxZti3oaWYfVFZuEFDrHotkJ4InNPfIsrHIExHW_K0sCLwfxf68nw01QbiNi878fOVlWfo784IH-F8TEF05tulevXRPKzcq6qtvaWyqmuyl64ljKbrcM0ssgAp5N-BNbgAcylZ-DbI2oFX7d7cjsZN9c5GoRU1yROzyQc6ktdRNMQUvNTmIMWPYZsD2q1vp655U1fVPBUILgc-xI_EGwyXJ1ABj2xB7Dthkz34LNzMFONzz-lA";
		String url = validator.getIssuerFromToken(token);
		Assert.assertEquals(url, "https://sso.vrigateway.com/auth/realms/sandbox");
		Key key = validator.getKeycloakPublicKey(url);
		Assert.assertNotNull(key);

		JwtClaims data = validator.verifyClaims(token, key);
		Assert.assertNotNull(data);

	}

}
